title:            The Devs of Vitals
description:      Developer blog.
# Your site's domain goes here. Leave localhost server or blank when working locally.
url:              'https://mdx-dev.github.io'
disqus_shortname:

# Owner/author information
author_ids: [blainesch, meetmicah, toddman0430, brandonwestcott]
authors:
  blainesch:
    name: Blaine Schmeisser
    display_name: BlaineSch
    gravatar: http://www.gravatar.com/avatar/ffebdf905fae3278a260ed03c9d165c7
    email: blainesch@gmail.com
    web: https://github.com/blainesch
    twitter: blainesch
    github: blainesch
    bio: "hello world"
  meetmicah:
    name: Micah Choquette
    display_name: Micah
    gravatar: http://www.gravatar.com/avatar/d1417fb0a0a205079e949a3ecfaee5f0
    email: osugodfan@gmail.com
    web: http://www.meetmicah.com
    twitter: meetmicah
    github: meetmicah
    bio: "Micah is a UX/UI Developer for Vitals with a passion for making sure that design is not just about how it looks, but how it works."
  toddman0430:
    name: Todd Emory
    display_name: Todd
    gravatar: http://www.gravatar.com/avatar/b4b6eed817248ed27a9468bd004434b1
    email: ctemory7@gmail.com
    web: https://github.com/toddman0430
    twitter: sequorveritas
    github: toddman0430
    bio: "Holistics, heuristics and linguistics."
  brandonwestcott:
    name: Brandon Westcott
    display_name: Brandon
    gravatar: http://www.gravatar.com/avatar/4bb6394946ec0877b791135eec3f5d29
    email: github@bwestcott.com
    web: https://github.com/brandonwestcott
    github: brandonwestcott
    bio: "It's kind of fun to do the impossible"

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Links to include in top navigation
# For external links add external: true
links:
  - title: Devs
    url: /devs/
  - title: Posts
    url: /posts/

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    America/New_York
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
